from pathlib import Path
import json
from urllib.parse import urlencode
R=Path(__file__).resolve().parent.parent
WA='https://wa.me/5519996414843?text=Ol%C3%A1%21%20Quero%20conhecer%20a%20OmniHub%20para%20minha%20empresa.'
WA_DEMO='https://wa.me/5519996414843?'+urlencode({'text':'Olá! Quero agendar uma demonstração da OmniHub para minha empresa.'})
plans=json.loads((R/'src/plans.json').read_text())
def money(v): return f'{v:,.2f}'.replace(',','X').replace('.',',').replace('X','.')
def checkout(p):
 ret='https://omnihub.site/obrigado/?'+urlencode(dict(plano=p['name'].lower(),ciclo='anual',valor=p['annual']))
 return 'https://app.omnihub.site/checkout?'+urlencode(dict(plan=p['name'],value=p['annual'],cycle='YEARLY',guarantee_days=30,card_only=1,return_url=ret))
arrow='<span aria-hidden="true">↗</span>'
logo='<img src="/assets/logo.webp" width="170" height="47" alt="OmniHub">'
header=f'''<a class="skip" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><div class="wrap nav"><a href="/" class="brand" aria-label="OmniHub — início">{logo}</a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Principal"><a href="/#personalizacao">Personalização <span class="nav-dot"></span></a><a href="/planos/">Planos</a><a href="https://app.omnihub.site" class="login">Entrar {arrow}</a><a class="button small light" href="{WA_DEMO}">Agendar demonstração {arrow}</a></nav></div></header>'''
footer=f'''<footer class="footer"><div class="wrap"><div class="footer-top"><a class="brand" href="/">{logo}</a><p>Atendimento, vendas e automação.<br>Conectados à sua operação.</p><a href="{WA}" class="text-link">Vamos conversar {arrow}</a></div><div class="footer-links"><div><span>PLATAFORMA</span><a href="/#plataforma">Recursos</a><a href="/#personalizacao">Personalização no anual</a><a href="/#integracoes">Integrações</a><a href="/planos/">Planos e preços</a></div><div><span>OMNIHUB</span><a href="/sobre/">Sobre nós</a><a href="https://www.vitalcore.com.br/" target="_blank" rel="noopener">Conheça a VitalCore ↗</a><a href="/condicoes/">Condições comerciais</a></div><div><span>FALE COM A GENTE</span><a href="{WA}">WhatsApp ↗</a><a href="https://www.instagram.com/use.omnihub/" target="_blank" rel="noopener">Instagram / @use.omnihub ↗</a><a href="https://app.omnihub.site">Acessar minha conta ↗</a></div></div><div class="footer-bottom"><span>© 2026 OmniHub. Uma solução VitalCore.</span><span>Relacionamentos movem negócios.</span></div></div></footer>'''
def page(title,desc,body,path='',noindex=False):
 schema={'@context':'https://schema.org','@type':'Organization','name':'OmniHub','url':'https://omnihub.site','logo':'https://omnihub.site/assets/logo.webp','sameAs':['https://www.instagram.com/use.omnihub/'],'parentOrganization':{'@type':'Organization','name':'VitalCore','url':'https://www.vitalcore.com.br/'}}
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><meta name="theme-color" content="#071c36"><meta name="google-site-verification" content="fr5wmhnkLUrRFdZlJ5WeFuo9M3Xpee2Pv4BbRFCl9nU"><link rel="canonical" href="https://omnihub.site/{path}">{'<meta name="robots" content="noindex,follow">' if noindex else ''}<meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:url" content="https://omnihub.site/{path}"><meta property="og:image" content="https://omnihub.site/assets/social.png"><meta property="og:image:alt" content="OmniHub. O sistema se adapta à sua empresa. Não o contrário."><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/inter-0.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><noscript><style>.delivery-tabs,.product-tabs{{display:none}}.delivery-panel[hidden]{{display:grid}}.delivery-panel{{margin-bottom:20px}}</style></noscript><script src="/app.js" defer></script></head><body>{header}<main id="conteudo">{body}</main>{footer}</body></html>'''
def price_section(full=False):
 cards=''
 for i,p in enumerate(plans):
  cards+=f'''<article class="price-card {'featured' if i==1 else ''}" data-plan="{i}"><div class="plan-number">0{i+1} / {p['name'].upper()}</div><h3>{p['name']}</h3><p class="plan-subtitle">{p['subtitle']}</p><div class="price"><span class="currency">R$</span> <strong data-price>{money(p['annual']/12)}</strong><span>/mês</span></div><p class="billing" data-billing>R$ {money(p['annual'])} cobrados ao ano</p><a class="button {'blue' if i==1 else 'outline'}" data-checkout href="{checkout(p)}">Escolher {p['name']} {arrow}</a><p class="included-users">Usuários e conexões ilimitados</p><ul>{''.join('<li>'+x+'</li>' for x in p['features'])}</ul><div class="annual-benefit" data-annual-benefit>↗ Personalização incluída no anual<span>Funcionalidades e integrações sob análise técnica.</span></div></article>'''
 return f'''<section class="pricing section" id="planos"><div class="wrap"><div class="section-heading"><div><span class="eyebrow">PLANOS QUE ACOMPANHAM SUA EMPRESA</span><h2>Capacidade para a operação.<br>Espaço para toda a equipe.</h2></div><div class="pricing-aside"><p>Usuários e conexões ilimitados em todos os planos. Escolha a capacidade para sua operação.</p><div class="billing-toggle" role="group" aria-label="Período de cobrança"><button data-cycle="monthly" aria-pressed="false">Mensal</button><button data-cycle="annual" aria-pressed="true">Anual <span>≈20% OFF</span></button></div></div></div><div class="price-grid">{cards}</div><div class="pricing-notes"><p data-guarantee>30 dias de garantia nos planos anuais.</p><p>Consumo de IA e serviços adicionais têm condições próprias. <a href="/condicoes/">Consultar condições ↗</a></p></div>{comparison() if full else '<a class="text-link dark-link" href="/planos/">Compare os recursos de cada plano '+arrow+'</a>'}</div></section>'''
def comparison():
 rows=[('Usuários e conexões','Ilimitados','Ilimitados','Ilimitados'),('Conversas por mês','3.000','15.000','Ilimitadas'),('Contatos','5.000','50.000','Ilimitados'),('Automações ativas','10','30','Ilimitadas'),('Agentes de IA','2','5','10'),('Integrações por webhook','5','20','Ilimitadas'),('Requisições de API / minuto','80','150','300'),('CRM e atendimento multicanal','Incluídos','Incluídos','Incluídos'),('Agenda, dashboard e drive','Incluídos','Incluídos','Incluídos'),('Personalização no anual¹','Incluída','Incluída','Incluída')]
 return '<div class="comparison"><h2>Olhe mais de perto.</h2><div class="table-scroll" tabindex="0" role="region" aria-label="Comparação dos planos"><table><thead><tr><th scope="col">Recurso</th><th scope="col">Essencial</th><th scope="col">Crescimento</th><th scope="col">Escala</th></tr></thead><tbody>'+''.join('<tr><th scope="row">'+r[0]+'</th>'+''.join('<td>'+c+'</td>' for c in r[1:])+'</tr>' for r in rows)+'</tbody></table></div><p class="fine">¹ Funcionalidades e integrações sujeitas à análise técnica e aderência ao propósito do CRM. Sem quantidade predefinida de solicitações.</p></div>'
clients=['Moby','Agência Koko','Deltec','Riro','CajuBrasil','Renata França','Grupo Filler','Plast & Co','Grupo Morecap','MyMerchan','Fábrica de Estudos','GFE','OxigenAr','Del Veneto','SuiteService','Mohave','Persol']
primary=[4,5,6,0,12,13]
def client_imgs(ids): return ''.join(f'<div class="client-logo"><img src="/assets/clientes/{i:02}.webp" alt="{clients[i]}" loading="lazy" width="180" height="75"></div>' for i in ids)
faq=[('Como funciona a personalização no plano anual?','Em qualquer plano anual, você pode solicitar funcionalidades e integrações para sua operação. As solicitações passam por análise técnica e são acompanhadas em um grupo de WhatsApp e em um roadmap privado. Não há uma quantidade predefinida de solicitações; a aprovação depende da viabilidade e da aderência ao propósito do CRM.'),('Vocês conseguem integrar o sistema que eu já uso?','A OmniHub já integra ferramentas de atendimento, pagamentos, jurídico, agenda, documentos, logística e automação, tanto na plataforma quanto em projetos personalizados. Entre elas estão Asaas, PayPal, Google Calendar, ADVBOX, ZapSign, Focus NFe e outras apresentadas na seção de integrações do site. Também temos APIs e webhooks próprios. No anual, avaliamos novas conexões com sistemas que tenham API. A equipe verifica a disponibilidade, o escopo e as condições de cada integração.'),('A OmniHub atende empresas do meu tamanho?','O foco são pequenas e médias empresas, inclusive equipes com até cerca de 100 funcionários. Todos os planos têm usuários e conexões ilimitados. A escolha depende do volume de conversas, contatos, automações e agentes de IA de que a sua operação precisa.'),('Preciso pagar por cada pessoa da equipe?','Não. Os planos Essencial, Crescimento e Escala incluem usuários e conexões ilimitados. Cada plano tem seus próprios limites de volume e de recursos.'),('Posso cancelar?','O mensal tem garantia de 7 dias e pode ser cancelado sem multa, mantendo o acesso até o fim do período pago. O anual tem garantia de 30 dias. Depois desse prazo, o cancelamento interrompe a próxima renovação, sem reembolso do período contratado, e o acesso continua até o fim da vigência.'),('O que preciso saber sobre IA e serviços adicionais?','A utilização de IA requer um provedor próprio, com consumo e condições à parte. Telefonia, gestão de Meta Ads, serviços jurídicos, financeiros e IA de sistemas adicionais são contratados separadamente. Consulte a equipe sobre condições dos canais e integrações para sua operação.')]
faqhtml='<section class="faq section"><div class="wrap faq-grid"><div><span class="eyebrow">DÚVIDAS FREQUENTES</span><h2>Antes de escolher.</h2><p>Quer falar sobre a sua operação?</p><a class="text-link dark-link" href="'+WA+'">Converse com a equipe '+arrow+'</a></div><div>'+''.join('<details><summary>'+q+'<span aria-hidden="true">+</span></summary><p>'+a+'</p></details>' for q,a in faq)+'</div></div></section>'
cta=f'<section class="closing"><div class="wrap"><div><p class="eyebrow">FALE COM A EQUIPE</p><h2>Vamos entender o que<br>sua empresa precisa.</h2></div><a class="button blue" href="{WA}">Conversar sobre a OmniHub {arrow}</a></div></section>'
deliveries=json.loads((R/'src/deliveries.json').read_text())
delivery_tabs=''.join(f'<button id="delivery-tab-{d["id"]}" role="tab" aria-selected="{str(i==0).lower()}" aria-controls="delivery-{d["id"]}" tabindex="{0 if i==0 else -1}" data-delivery-tab="{d["id"]}"><span>0{i+1}</span><strong>{d["name"]}</strong><small>{d["category"]}</small></button>' for i,d in enumerate(deliveries))
delivery_panels=''
for i,d in enumerate(deliveries):
 actions=''.join(f'<li><span aria-hidden="true">0{j+1}</span>{action}</li>' for j,action in enumerate(d['actions']))
 delivery_panels+=f'''<article class="delivery-panel" id="delivery-{d['id']}" role="tabpanel" aria-labelledby="delivery-tab-{d['id']}" tabindex="0" {"hidden" if i else ""}><div class="delivery-feature"><span class="delivery-category">{d['category'].upper()} / INTEGRAÇÃO PERSONALIZADA</span><h3>{d['headline']}</h3><ol>{actions}</ol></div><div class="delivery-detail"><div><h4>O que o cliente precisava</h4><p>{d['need']}</p></div><div><h4>O que entregamos</h4><p>{d['delivery']}</p></div><div><h4>Como é usado</h4><p>{d['usage']}</p></div><a class="text-link" href="#customization-form" data-case-request="{d['id']}">Avaliar algo parecido <span aria-hidden="true">→</span></a></div></article>'''
delivery_html=(R/'src/deliveries.html').read_text().replace('{{DELIVERY_TABS}}',delivery_tabs).replace('{{DELIVERY_PANELS}}',delivery_panels)
(R/'assets/deliveries.json').write_text(json.dumps(deliveries,ensure_ascii=False))
planrows=''.join(f'<article class="plan-row"><div><h3>{p["name"]}</h3><p>{p["features"][0]} · {p["features"][1]}</p></div><div class="row-price"><span>R$ <strong>{money(p["annual"]/12)}</strong> /mês</span><small>R$ {money(p["annual"])} cobrados ao ano</small></div><a href="/planos/" aria-label="Ver detalhes do plano {p["name"]}">Ver plano <span aria-hidden="true">↗</span></a></article>' for p in plans)
integrations=json.loads((R/'src/integrations.json').read_text())
brand_ids={'Meta':'meta','Twilio':'twilio','Gupshup':'gupshup','Wavoip':'wavoip','TecnoVoz':'tecnovoz','TecnoVoz':'tecnovoz','Asaas':'asaas','PayPal':'paypal','Greenn':'greenn','Hotmart':'hotmart','Kiwify':'kiwify','ADVBOX':'advbox','Judit':'judit','Google Calendar':'google-calendar','ZapSign':'zapsign','Lalamove':'lalamove','Focus NFe':'focus-nfe','n8n':'n8n'}
brand_sources=json.loads((R/'assets/integracoes/sources.json').read_text())
brand_cards=[]
for group in integrations:
 for name in group['names']:
  slug=brand_ids.get(name)
  if not slug:continue
  name='TecnoVoz' if slug=='tecnovoz' else name
  dark=' brand-art-dark' if slug in ['advbox','n8n','asaas'] else ''
  brand_cards.append(f'<div class="integration-brand"><div class="brand-art{dark}"><img src="/assets/integracoes/{brand_sources[slug]["file"]}" alt="Logo {name}" width="150" height="60" loading="lazy"></div><strong>{name}</strong><span>{group["category"]}</span></div>')
integration_groups=''
for i,row in enumerate([brand_cards[:9],brand_cards[9:]]):
 sequence=''.join(row)
 integration_groups+=f'<div class="integration-marquee" role="region" aria-label="Integrações da OmniHub, faixa {i+1}"><div class="integration-track {"reverse" if i else ""}"><div class="integration-sequence">{sequence}</div><div class="integration-sequence" aria-hidden="true">{sequence}</div></div></div>'
home=(R/'src/home.html').read_text()
for token,value in {'WA':WA,'CLIENTS':client_imgs(range(len(clients))),'PLAN_ROWS':planrows,'FAQ':faqhtml,'CUSTOMER_STORY':delivery_html,'INTEGRATION_GROUPS':integration_groups}.items():
 home=home.replace('{{'+token+'}}',value)
(R/'index.html').write_text(page('OmniHub | O CRM que se adapta à sua empresa','Sua empresa não precisa se adaptar às limitações do software. Reúna CRM e atendimento com personalização de funcionalidades e integrações no anual, sob análise técnica.',home))
subhero=lambda label,title,desc:f'<section class="subhero"><div class="wrap"><span class="eyebrow">{label}</span><h1>{title}</h1><p>{desc}</p></div></section>'
planbody=subhero('PLANOS E PREÇOS','Escolha a capacidade.<br>Inclua toda a equipe.','A mesma plataforma, com diferentes capacidades. No anual, desconto e personalização para aproximar o sistema da sua operação.')+price_section(True)+faqhtml+cta
about=subhero('SOBRE A OMNIHUB','Conheça a OmniHub.<br>Uma solução VitalCore.','A OmniHub é uma solução VitalCore que reúne CRM, atendimento e automação para pequenas e médias empresas.')+f'''<section class="section"><div class="wrap prose-grid"><h2>Uma plataforma para<br>a rotina da sua empresa.</h2><div class="prose"><p>Uma empresa não se resume ao funil de vendas. Existem conversas, pessoas, tarefas e sistemas que precisam trabalhar juntos.</p><p>A OmniHub reúne atendimento multicanal, CRM, automações, agentes de IA, agenda, dashboard e drive em uma plataforma. O foco está nas pequenas e médias empresas, inclusive equipes com até cerca de 100 funcionários.</p><h2>Um sistema que acompanha a operação.</h2><p>Em todos os planos anuais, a personalização de funcionalidades e integrações faz parte da oferta. As necessidades são avaliadas tecnicamente, com acompanhamento por grupo de WhatsApp e roadmap privado.</p><p>Essa proximidade permite entender o que faz sentido para cada negócio, respeitando a viabilidade e o propósito do CRM.</p><h2>Por trás da OmniHub, a VitalCore.</h2><p>Conheça a empresa responsável pela plataforma ou fale com a equipe para entender como a OmniHub pode se encaixar no seu dia a dia.</p><a class="button blue" href="https://www.vitalcore.com.br/" target="_blank" rel="noopener">Conheça a VitalCore {arrow}</a></div></div></section>'''+cta
conditions=subhero('CONDIÇÕES COMERCIAIS','Escolha com<br><em>clareza.</em>','As condições principais dos planos, da personalização e dos serviços adicionais.')+f'''<section class="section"><div class="wrap prose narrow"><h2>Mensal e anual</h2><p>O plano mensal tem garantia de 7 dias. Pode ser cancelado sem multa, com acesso até o fim do período pago.</p><p>O anual é cobrado pelo valor total do período e tem garantia de 30 dias. Após esse prazo, o cancelamento interrompe a próxima renovação, sem reembolso do período contratado. O acesso permanece até o fim da vigência paga.</p><h2>Personalização no anual</h2><p>Todos os níveis anuais incluem a possibilidade de solicitar funcionalidades e integrações. Não há uma quantidade predefinida de solicitações. Cada demanda depende de análise técnica, viabilidade e aderência ao propósito do CRM. Solicitações fora desse escopo podem ser recusadas.</p><p>O acompanhamento acontece por um grupo de WhatsApp e por um roadmap privado. Não há promessa de aprovação automática ou de prazo único para todas as demandas.</p><h2>Integrações, IA e serviços adicionais</h2><p>Novas integrações com sistemas externos exigem API disponível e passam por análise técnica. Disponibilidade, requisitos e condições dos provedores externos devem ser verificados para cada operação.</p><p>O uso de IA exige um provedor próprio e está sujeito às respectivas condições e consumo. Telefonia, gestão de Meta Ads, serviços jurídicos, financeiros e IA de sistemas adicionais são cobrados separadamente.</p><h2>Antes de contratar</h2><p>Confira o plano, o ciclo de cobrança e o total na página de contratação. Para confirmar a compatibilidade de uma integração ou esclarecer condições da sua operação, fale com a equipe.</p><a class="button blue" href="{WA}">Esclarecer uma dúvida {arrow}</a><p class="fine">Este resumo comercial não substitui os instrumentos contratuais apresentados na contratação.</p></div></section>'''
thanks=subhero('SUA CONTRATAÇÃO','Vamos para<br><em>o próximo passo.</em>','Confira a confirmação da contratação na sua conta ou no canal informado durante o pagamento.')+f'<section class="section"><div class="wrap prose narrow"><p>Esta página de retorno não confirma, por si só, a aprovação do pagamento. Consulte sua conta para acompanhar a situação.</p><a class="button blue" href="https://app.omnihub.site">Acessar minha conta {arrow}</a><p>Precisa de ajuda? <a href="{WA}">Fale com a equipe pelo WhatsApp.</a></p></div></section>'
for slug,title,desc,body in [('planos','Planos e preços | OmniHub','Compare os planos Essencial, Crescimento e Escala da OmniHub, com usuários ilimitados e personalização nos planos anuais.',planbody),('sobre','Sobre a OmniHub | Uma solução VitalCore','Conheça a OmniHub, solução VitalCore de CRM, atendimento e automação para pequenas e médias empresas.',about),('condicoes','Condições comerciais | OmniHub','Consulte as condições de cobrança, garantia, cancelamento e personalização dos planos OmniHub.',conditions),('obrigado','Próximos passos | OmniHub','Consulte a situação da sua contratação OmniHub.',thanks)]:
 (R/slug).mkdir(exist_ok=True)
 (R/slug/'index.html').write_text(page(title,desc,body,slug+'/',slug=='obrigado'))
(R/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: https://omnihub.site/sitemap.xml\n')
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://omnihub.site/'+p+'</loc></url>' for p in ['','planos/','sobre/','condicoes/'])+'</urlset>')
(R/'_redirects').write_text('/planos /planos/ 301\n/sobre /sobre/ 301\n/condicoes /condicoes/ 301\n/obrigado /obrigado/ 301\n')
(R/'assets/plans.json').write_text(json.dumps(plans,ensure_ascii=False))
notfound=subhero('PÁGINA NÃO ENCONTRADA','Vamos encontrar<br>o caminho certo.','O endereço que você acessou não corresponde a uma página do site.')+'<section class="section"><div class="wrap"><a class="button blue" href="/">Voltar para a OmniHub →</a></div></section>'
(R/'404.html').write_text(page('Página não encontrada | OmniHub','Acesse a página inicial para conhecer a OmniHub.',notfound,'404',True))
print('Built 6 pages.')
